# Generated by Django 3.2.25 on 2024-08-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogianna_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_submitted',
            new_name='created_at',
        ),
    ]
