# Generated by Django 3.2.25 on 2024-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogianna_web', '0002_rename_date_submitted_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
