# Generated by Django 3.2.25 on 2024-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogianna_web', '0003_auto_20240828_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='books/')),
                ('pdf_link', models.FileField(upload_to='books-PDF/')),
            ],
        ),
    ]
