# Generated by Django 3.2.25 on 2024-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogianna_web', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-30 00:00:00'),
            preserve_default=False,
        ),
    ]
